### ISSUE TITLE
Impossible to change output path

### ISSUE THREAD

**Issue by Zi0MIX** [schneidermanuel/TwitchLeecher-Dx#15]
**Description**
It is impossible to change output patch during download video step, i have no choice but to download to directory specified as download folder in the settings

**Steps to reproduce**
Little context here, i use 2 different drives for downloads, one for temps and one for actual downloads, and none of them is a C drive. Here are my settings
![image](https://github.com/schneidermanuel/TwitchLeecher-Dx/assets/80110206/faad3c13-f5cc-4da7-80d8-3674b4134665)

While downloading I'm trying to select a subdirectory on E drive, and after doing so my output folder remains as shown on the screenshot and the VOD is in fact being downloaded to E:\

**Information**
- I tried on multiple random VODs
- Windows 10 PRO 64bit 22H2

**Additional information that might be useful**
Additionally the field does behave like it's possible to just paste the path in there, if i remember correctly it was never an option to just paste the path, so i think either allowing pasting the path manually or making it appear as read only would clear the confusion

**Comment by schneidermanuel** [comment]
Yeah, I noticed that the Buttons (...) do not work, I also fixed this with #14.
I will try my best to get a new release out by tomorrow. Since I am using Linux, It always takes some time for me to compile and test a Windows-Release.

**Comment by FlamingPhoenix40** [comment]
Looking at releases, 3.5 should be the version that fixes #15, #12 and #11, which are the issues mentioned in #14. However, I still cannot change the path using the (...) button.

**Comment by schneidermanuel** [comment]
Reproduced. 
Interesting, cause this worked for me (using Linux). 
I will have a deeper look at this!
